name: Update Commander Database

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-database:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: pip install pandas openpyxl

    - name: Run update script
      run: python update_spreadsheet.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add RTW_commanders_database.xlsx latest_RTW_commanders_database.csv
        git commit -m "Auto-updated commander database and CSV" || echo "No changes to commit"
        git push
